services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/webapps
        #	mariadb:
        #		image: mariadb
        #        build: ./requirements/mariadb
        #        volume:
        #        - db:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/usr/share/webapps
volumes:
  db:
  wordpress:
