services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/webapps

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/usr/share/webapps

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes:
    #  - db:/var/lib/mysql

volumes:
  db:
  wordpress:
