networks:
  docker-network:
    name: ${NETWORK}


services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - type: bind
        source: /home/jio/data/wordpress
        target: /usr/share/webapps
    networks:
      - ${NETWORK}

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - DB=${MYSQL_DATABASE}
        - USER=${MYSQL_USER}
        - PASSWORD=${MYSQL_PASSWORD}
        - HOST=mariadb
    volumes:
      - type: bind
        source: /home/jio/data/wordpress
        target: /usr/share/webapps
    networks:
      - ${NETWORK}

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        - ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - USER=${MYSQL_USER}
        - PASSWORD=${MYSQL_PASSWORD}
        - DATABASE=${MYSQL_DATABASE}
        - DOMAIN=${NETWORK}
    volumes:
      - type: bind
        source: /home/jio/data/db
        target: /var/lib/mysql/wordpress
    networks:
      - ${NETWORK}

