services:

  # TODO: Only allow nginx to communicate with wordpress; and wordpress with mariadb (ports, network_mode)
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/usr/share/webapps
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/usr/share/webapps
    networks:
      - docker-network

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - USER=${MYSQL_USER}
        - PASSWORD=${MYSQL_PASSWORD}
        - DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql/wordpress
    networks:
      - docker-network

volumes:
  db:
    name: db
  wordpress:
    name: wordpress

networks:
  docker-network:
    name: docker-network
